### ISSUE TITLE
PyPI: relative links in README.md break in long_description

### ISSUE THREAD

**Issue by ColinKCurtis** [dhimmel/obonet#12]
I just wanted to give you a heads up that the link: https://pypi.org/project/obonet/examples/go-obonet.ipynb ( which is located at https://pypi.org/project/obonet/ ) is currently returning a 404.

**Comment by dhimmel** [comment]
The issue is that [`README.md`](https://github.com/dhimmel/obonet/blob/f435b74d2b88b454dc0a8d6a18055c6671a64d28/README.md#usage) uses [relative links](https://github.blog/2013-01-31-relative-links-in-markup-files/). I'll see if there is a good workaround so we can keep the relative links but expand them for `setup.py`'s `long_description` argument, which is how the README gets set for PyPI. If not, I'll probably leave the links broken, since I think value relative links in the repository over perfection on PyPI.

**Comment by dhimmel** [comment]
Similar issue to https://github.com/pysal/pointpats/issues/8 / https://github.com/hypatia-software-org/hypatia-engine/issues/124 / https://github.com/senaite/senaite.sync/issues/61

**Comment by dhimmel** [comment]
In https://github.com/dhimmel/obonet/commit/5eaafa835adea21b76420a91f40f7c696ef4aad6 I switched to absolute links, following the lead of the other projects in the previous comment. However, the links were still broken (for another reason, fixed in https://github.com/dhimmel/obonet/commit/12ae7d635b2abb1ff5b14ff4a0c4d3a23ce6de04). Now, the links are finally fixed on PyPI as of v0.2.5. See https://pypi.org/project/obonet/0.2.5/

Thanks @ColinKCurtis for the initial report!
