### ISSUE TITLE
Save as an obo file

### ISSUE THREAD

**Issue by MahboobehJannesari** [dhimmel/obonet#17]
Hi,

I would like is it possible to save a graph as obo file using obonet?
I load an obo file and change some part pf graph, I want to save it as a new obo file.

best
Mahboubeh

**Comment by dhimmel** [comment]
obonet does not support writing to `.obo` files, only reading into a networkx graph.

Some other projects that might allow you to write obo are:

- https://github.com/fastobo/fastobo-py
- https://github.com/althonos/pronto

I will close this issue because I think writing .obo is out of scope for this repository. But please do update if either of these solutions work for you, in case others find that helpful.
