### ISSUE TITLE
Add encoding parameter in read_obo function

### ISSUE THREAD

**Issue by gtsitsiridis** [dhimmel/obonet#28]
I am trying to read an obo file that is in utf-8. I have to manually adjust the library to make that work. The obo file I am using is: https://github.com/HUPO-PSI/psi-mi-CV/blob/master/psi-mi.obo

**Comment by dhimmel** [comment]
470e2efdea4797fd36cb5f701e0bb1ce1d4e99c4 added an `encoding` option to `obonet.read_obo` that defaults to utf-8. Will let you know when a new release is available with this commit (sometime today).

**Comment by dhimmel** [comment]
v1.0.0 released [here](https://github.com/dhimmel/obonet/releases/tag/v1.0.0) and on [PyPI](https://pypi.org/project/obonet/1.0.0/). Would love if you could give a try and see if this issue is fixed (as well as confirm that the package installs properly), since we've switched entirely to `pyproject.toml`.

**Comment by dhimmel** [comment]
Should be fixed, but @gtsitsiridis let us know if otherwise.
